/* jQuery Html Editor Plugin for WYSIWYG Web Builder 16 - Copyright Pablo Software solutions 2020 -  http://www.wysiwygwebbuilder.com */
(function(a){a.fn.wwbeditor=function(f){var d=a.extend({buttons:{undo:!1,redo:!1,bold:!0,italic:!0,underline:!0,strikethrough:!0,justifyleft:!0,justifycenter:!0,justifyright:!0,justifyfull:!0,insertorderedlist:!0,insertunorderedlist:!0,indent:!0,outdent:!0,createLink:!0,unlink:!0,insertimage:!0,uploadimage:!0,inserthorizontalrule:!1,cut:!1,copy:!1,paste:!1,forecolor:!0,hilitecolor:!0,br:!0,formatblock:!0,fontname:!0,fontsize:!0}},f);return this.each(function(){a.wwbeditor(a(this),d)})};var k,q=!1,
r;a.wwbeditor=function(f,d){function l(a,c,g){d.iframe[0].contentWindow.focus();d.iframe[0].contentWindow.document.execCommand(a,c,g);d.textarea.val(d.iframe[0].contentWindow.document.body.innerHTML)}function w(){if(d.iframe[0].contentWindow.window.getSelection){if(sel=d.iframe[0].contentWindow.window.getSelection(),sel.getRangeAt&&sel.rangeCount)return sel.getRangeAt(0)}else if(d.iframe[0].contentWindow.document.selection&&d.iframe[0].contentWindow.document.selection.createRange)return d.iframe[0].contentWindow.document.selection.createRange();
return null}function t(b){var c="#"+d.colorpickerid,g=a(b.target).parents(c).length;b.target==a(c)[0]||b.target==k||0<g||p(!1)}function p(b){var c=a("#"+d.colorpickerid);b?(r=w(),c.css("top",a(k).offset().top+a(k).outerHeight()),c.css("left",a(k).offset().left),c.show(),a(document).bind("mousedown",t)):(a(document).unbind("mousedown",t),c.hide());q=b}f.width();var e=f.height()-4,u=f.position(),h=a("<div class='wwbeditor' />");h.insertAfter(f);var n=a("<iframe/>").height(e).css("border-width",0);d.iframe=
n;d.textarea=f;d.id=f.attr("id");(function(){d.colorpickerid="color_picker_"+d.id;a("#"+d.colorpickerid).remove();var b=a("<div class='wwbeditor-color_picker'/>");b.attr("id",d.colorpickerid);b.css("z-index","2500");a.each("#000000 #A52A00 #004040 #005500 #00005E #00008B #4B0082 #282828 #8B0000 #FF6820 #8B8B00 #009300 #388E8E #0000FF #7B7BC0 #666666 #FF0000 #FFAD5B #32CD32 #3CB371 #7FFFD4 #7D9EC0 #800080 #7F7F7F #FFC0CB #FFD700 #FFFF00 #00FF00 #40E0D0 #C0FFFF #480048 #C0C0C0 #FFE4E1 #D2B48C #FFFFE0 #98FB98 #AFEEEE #68838B #E6E6FA #FFFFFF".split(" "),
function(c){c=a("<div class='wwbeditor-color_picker_cell'>&nbsp;</div>");c.css("background-color",this);c.bind("mouseover",function(d){a(this).css("border-color","#598FEF")});c.bind("mouseout",function(d){a(this).css("border-color","#000000")});c.bind("click",function(c){c=a(this).css("background-color");var g=a(k).attr("title"),b=r;b&&(d.iframe[0].contentWindow.window.getSelection?(sel=d.iframe[0].contentWindow.window.getSelection(),sel.removeAllRanges(),sel.addRange(b)):d.iframe[0].contentWindow.document.selection&&
b.select&&b.select());l(g,!1,c);p(!1)});c.appendTo(b)});a("body").append(b);b.hide()})();(function(){d.imageuploadid="image-upload"+d.id;a("#"+d.imageuploadid).remove();var b=a("<div class='wwbeditor-image-upload-popup'/>");b.attr("id",d.imageuploadid);var c=a("<div class='wwbeditor-image-upload'>"),g=a("<div class='wwbeditor-close'></div>"),f=a("<div style='padding: 10px;'><div class='wwbeditor-text'>Insert an Image</div><input type='file'><progress style='width: 100%; display: none;'></progress></div>");
c.append(g);c.append(f);b.append(c);g.bind("click",function(c){a("#"+d.imageuploadid).hide()});c.find("input").on("change",function(c){if((c=this.files[0])&&c.type.match(/image.*/)){var b=new FileReader;b.onloadend=function(){l("insertImage",!1,b.result)};b.readAsDataURL(c);a("#"+d.imageuploadid).hide()}else alert("Only image files can be uploaded")});a("body").append(b);b.hide()})();(function(b){var c=a('<div class="wwbeditor-toolbar" />');c.attr("unselectable","on");a.each(d.buttons,function(b,
f){if(f)if("formatblock"==b){var e=a('<select id="formatblock"><option value="<p>">Normal</option><option value="<h1>">Heading 1 <h1></option><option value="<h2>">Heading 2 <h2></option><option value="<h3>">Heading 3 <h3></option><option value="<h4>">Heading 4 <h4></option><option value="<h5>">Heading 5 <h5></option><option value="<h6>">Heading 6 <h6></option></select>');e.change(function(){var b=a(this).find(":selected").val();l("formatBlock",!1,b)});c.append(e)}else if("fontname"==b){var g=a('<select id="fontname" />');
a.each("Arial;Comic Sans MS;Courier New;Georgia;Impact;Sans Serif;Serif;Tahoma;Times New Roman;Trebuchet MS;Verdana".split(";"),function(b,c){g.append(a("<option />").attr("value",c).text(c))});g.change(function(){var b=a(this).find(":selected").val();l("fontName",!1,b)});c.append(g)}else if("fontsize"==b){var h=a('<select unselectable="on" id="fontsize" />');a.each("1234567".split(""),function(b,c){h.append(a("<option />").attr("value",c).text(c))});h.change(function(){var b=a(this).find(":selected").val();
l("fontSize",!1,b)});c.append(h)}else"br"==b?c.append("<br>"):(e=a("<img />"),e.attr("src","./wwbeditor/images/"+b+".png"),e.attr("alt",b),e.attr("title",b),e.attr("unselectable","on"),e.bind("click",function(c){"insertimage"==b||"createLink"==b?(c=prompt("Enter URL:","http://"),l(b,!1,c)):"forecolor"==b||"hilitecolor"==b?(k=this,p(!q)):"uploadimage"==b?(k=this,c=a("#"+d.imageuploadid),c.css("top",a(k).offset().top+a(k).outerHeight()),c.css("left",a(k).offset().left-c.outerWidth()/2),c.show()):l(b,
!1,null)}),c.append(e))});c.appendTo(b)})(h);var v=a("<div/>").append(n);v.addClass("wwbeditor-content");h.append(v).append(f);f.hide();var m=n[0].contentWindow.document;m.designMode="on";m.open();m.write(f.val());m.close();a(m.body).css({margin:0,padding:0});"absolute"==f.css("position")&&(h.css("position","absolute"),h.css("left",u.left),h.css("top",u.top));e-=h.find(".wwbeditor-toolbar").height();n.height(e);e=function(){f.val(m.body.innerHTML)};a(m.body).click(e).blur(e).keydown(e).keyup(e).mousedown(e)}})(jQuery);